# Generated by Django 5.1.15 on 2026-06-07 21:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_id', models.CharField(help_text='ID vindo da API simulada de SP', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Coordenadas exatas do estacionamento', srid=4326)),
                ('total_capacity', models.IntegerField(default=0)),
                ('occupied_spots', models.IntegerField(default=0)),
                ('available_spots', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=12.0, help_text='Valor cobrado por hora', max_digits=6)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('LOTANDO', 'Lotando'), ('LOTADO', 'Lotado'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20)),
                ('last_sensor_update', models.DateTimeField(blank=True, help_text='Última vez que o simulador atualizou os dados', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estacionamento',
                'verbose_name_plural': 'Estacionamentos',
                'ordering': ['-available_spots'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Em Andamento'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parking.parking')),
            ],
        ),
    ]
