# Generated by Django 5.1.15 on 2026-04-04 15:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_id', models.CharField(help_text='ID vindo da API simulada de SP', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Coordenadas exatas do estacionamento', srid=4326)),
                ('total_capacity', models.IntegerField(default=0)),
                ('occupied_spots', models.IntegerField(default=0)),
                ('available_spots', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('LOTANDO', 'Lotando'), ('LOTADO', 'Lotado'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20)),
                ('last_sensor_update', models.DateTimeField(blank=True, help_text='Última vez que o simulador atualizou os dados', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estacionamento',
                'verbose_name_plural': 'Estacionamentos',
                'ordering': ['-available_spots'],
            },
        ),
    ]
