# Generated by Django 5.1.15 on 2026-06-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkin_token',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'A Caminho'), ('ACTIVE', 'Em Andamento'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20),
        ),
    ]
