# Generated by Django 5.1.15 on 2026-06-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_booking_checkin_token_alter_booking_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'A Caminho'), ('ACTIVE', 'Em Andamento'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='RESERVED', max_length=20),
        ),
    ]
