# Generated by Django 5.1.15 on 2026-04-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_plate',
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
