# Generated by Django 5.1.15 on 2026-06-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='spot_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local da Vaga'),
        ),
    ]
